[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "bskpdf"
requires-python = ">=3.11"
dependencies = [
    "requests",
    'importlib-metadata; python_version<"3.10"',
]
version = "0.0.1"
