[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "bskpdf"
requires-python = ">=3.11"
dependencies = [
    "cryptography>=44.0.2",
    "dearpygui>=2.0.0",
]
version = "0.0.1"

[project.scripts]
bskpdf = "bskpdf.gui:gui"